// Mock preloaded state for UI-only mode
// This fills all Redux slices with realistic mock data so the UI renders without a backend

const MOCK_USER = {
  _id: "usr-001",
  name: "Rahul Sharma",
  email: "rahul@example.com",
  phone: "+91 9876543210",
  mobile: "+91 9876543210",
  profilePicture: "",
  ongoingJobs: 2,
  completedJobs: 5,
};

const MOCK_SERVICES = [
  { _id: "svc-001", name: "AI Engineer", category: "ai-engineer", description: "Expert AI engineers for ML/NLP/LLM projects", hourlyRate: 2000, icon: "/images/homepage/AI.svg", rating: 4.9, reviews: 142, skills: ["Python", "TensorFlow", "PyTorch", "LangChain"] },
  { _id: "svc-002", name: "Full Stack Developer", category: "developer", description: "Expert full-stack developers for web projects", hourlyRate: 1500, icon: "/images/homepage/developer.png", rating: 4.8, reviews: 210, skills: ["React", "Node.js", "MongoDB", "PostgreSQL"] },
  { _id: "svc-003", name: "UI/UX Designer", category: "designer", description: "Creative designers for web and mobile apps", hourlyRate: 1200, icon: "/images/homepage/designer.png", rating: 4.7, reviews: 98, skills: ["Figma", "Adobe XD", "Prototyping"] },
  { _id: "svc-004", name: "DevOps Engineer", category: "devops", description: "Cloud and DevOps specialists", hourlyRate: 1800, icon: "/images/homepage/deveops.png", rating: 4.8, reviews: 76, skills: ["AWS", "Docker", "Kubernetes", "CI/CD"] },
  { _id: "svc-005", name: "Quality Assurance", category: "quality-assurance", description: "QA engineers for manual and automation testing", hourlyRate: 1000, icon: "/images/homepage/quality.png", rating: 4.6, reviews: 55, skills: ["Selenium", "Cypress", "Jest", "Postman"] },
  { _id: "svc-006", name: "Security Engineer", category: "security", description: "Cybersecurity experts to protect your systems", hourlyRate: 2200, icon: "/images/homepage/secqurity.png", rating: 4.9, reviews: 41, skills: ["VAPT", "OWASP", "Penetration Testing"] },
];

const MOCK_ONGOING_BOOKINGS = [
  {
    _id: "bkg-001",
    bookingId: "BK-10023",
    serviceName: "Full Stack Developer",
    serviceId: "svc-002",
    projectTitle: "E-commerce Platform Revamp",
    status: "ongoing",
    startDate: "2026-04-01T10:00:00Z",
    assignedExpert: "Priya Singh",
    projectManagerName: "Amit Kumar",
    hourlyRate: 1500,
    totalHours: 80,
    amountPaid: 120000,
    statusType: "ongoing",
    projectManagerId: "pm-001",
    assignedResourceId: "res-001",
    technologyIds: ["React", "Node.js"],
  },
  {
    _id: "bkg-002",
    bookingId: "BK-10024",
    serviceName: "DevOps Engineer",
    serviceId: "svc-004",
    projectTitle: "CI/CD Pipeline Setup",
    status: "ongoing",
    startDate: "2026-04-10T10:00:00Z",
    assignedExpert: "Ravi Verma",
    projectManagerName: "Sneha Gupta",
    hourlyRate: 1800,
    totalHours: 40,
    amountPaid: 72000,
    statusType: "ongoing",
    projectManagerId: "pm-002",
    assignedResourceId: "res-002",
    technologyIds: ["Docker", "Kubernetes"],
  },
];

const MOCK_COMPLETED_BOOKINGS = [
  {
    _id: "bkg-003",
    bookingId: "BK-10015",
    serviceName: "UI/UX Designer",
    serviceId: "svc-003",
    projectTitle: "Mobile App Redesign",
    status: "completed",
    startDate: "2026-02-15T10:00:00Z",
    endDate: "2026-03-15T10:00:00Z",
    assignedExpert: "Anjali Mehta",
    hourlyRate: 1200,
    totalHours: 60,
    amountPaid: 72000,
  },
  {
    _id: "bkg-004",
    bookingId: "BK-10008",
    serviceName: "Quality Assurance",
    serviceId: "svc-005",
    projectTitle: "API Testing Suite",
    status: "completed",
    startDate: "2026-01-10T10:00:00Z",
    endDate: "2026-02-10T10:00:00Z",
    assignedExpert: "Karan Tiwari",
    hourlyRate: 1000,
    totalHours: 50,
    amountPaid: 50000,
  },
];

const MOCK_NOTIFICATIONS = [
  {
    _id: "ntf-001",
    title: "Booking Confirmed",
    message: "Your booking BK-10024 for DevOps Engineer has been confirmed.",
    isRead: false,
    type: "booking",
    createdAt: "2026-04-10T11:00:00Z",
  },
  {
    _id: "ntf-002",
    title: "Expert Assigned",
    message: "Priya Singh has been assigned to your Full Stack Developer project.",
    isRead: false,
    type: "booking",
    createdAt: "2026-04-02T09:00:00Z",
  },
  {
    _id: "ntf-003",
    title: "Payment Successful",
    message: "Payment of ₹1,20,000 for BK-10023 has been received.",
    isRead: true,
    type: "payment",
    createdAt: "2026-04-01T14:30:00Z",
  },
];

const MOCK_PAYMENT_HISTORY = [
  {
    _id: "pay-001",
    jobId: "job-001",
    serviceName: "Full Stack Developer",
    projectTitle: "E-commerce Platform Revamp",
    amount: 120000,
    gstAmount: 21600,
    totalAmount: 141600,
    status: "paid",
    date: "2026-04-01T14:00:00Z",
    invoiceNumber: "INV-2026-001",
    paymentMethod: "Online",
  },
  {
    _id: "pay-002",
    jobId: "job-002",
    serviceName: "DevOps Engineer",
    projectTitle: "CI/CD Pipeline Setup",
    amount: 72000,
    gstAmount: 12960,
    totalAmount: 84960,
    status: "paid",
    date: "2026-04-10T12:00:00Z",
    invoiceNumber: "INV-2026-002",
    paymentMethod: "Online",
  },
  {
    _id: "pay-003",
    jobId: "job-003",
    serviceName: "UI/UX Designer",
    projectTitle: "Mobile App Redesign",
    amount: 72000,
    gstAmount: 12960,
    totalAmount: 84960,
    status: "paid",
    date: "2026-03-15T10:00:00Z",
    invoiceNumber: "INV-2026-003",
    paymentMethod: "Online",
  },
];

const MOCK_TICKETS = [
  {
    _id: "tkt-001",
    ticketId: "TK-0042",
    subject: "Payment not reflected",
    status: "open",
    priority: "high",
    description: "I made a payment 2 days ago but it is not showing in my booking.",
    createdAt: "2026-04-20T10:00:00Z",
    bookingId: "BK-10023",
    bookingName: "E-commerce Platform Revamp",
  },
  {
    _id: "tkt-002",
    ticketId: "TK-0038",
    subject: "Expert response delayed",
    status: "resolved",
    priority: "medium",
    description: "The assigned expert has not responded for 2 days.",
    createdAt: "2026-04-12T14:00:00Z",
    resolvedAt: "2026-04-14T09:00:00Z",
    bookingId: "BK-10024",
    bookingName: "CI/CD Pipeline Setup",
  },
];

export const mockPreloadedState = {
  auth: {
    user: null,
    token: null,
    guestToken: null,
    userType: null,
    isAuthenticated: false,
    isNewUser: false,
    isLoading: false,
    error: null,
    otpSent: false,
    guestData: null,
  },
  booking: {
    selectedService: null,
    serviceDetails: null,
    selectedTechnologies: [],
    selectedDuration: null,
    selectedDate: null,
    selectedTime: null,
    currentStep: 1,
    totalSteps: 4,
    currentBooking: null,
    bookingHistory: [],
    customerBookings: [],
    ongoingBookings: [],
    ongoingBookingsPagination: null,
    completedBookings: [],
    completedBookingsPagination: null,
    selectedJobId: null,
    jobDetails: null,
    createdJob: null,
    updatedJob: null,
    createdJobId: null,
    totalPrice: 0,
    isLoading: false,
    isCreatingBooking: false,
    isFetchingCustomerBookings: false,
    isFetchingOngoingBookings: false,
    isFetchingCompletedBookings: false,
    isFetchingJobDetails: false,
    isCreatingJob: false,
    isUpdatingJob: false,
    error: null,
  },
  user: {
    user: null,
    isLoading: false,
    error: null,
  },
  services: {
    allServices: [],
    selectedService: null,
    filteredServices: [],
    searchQuery: "",
    selectedCategory: "all",
    isLoading: false,
    isLoadingDetail: false,
    error: null,
    categories: ["all", "frontend", "backend", "design", "qa", "devops", "mobile"],
  },
  userProfile: {
    profile: null,
    isLoading: false,
    error: null,
  },
  availability: {
    hoursAvailability: null,
    availableSlots: [],
    selectedDuration: null,
    isLoading: false,
    error: null,
  },
  pricing: {
    pricing: null,
    isLoading: false,
    error: null,
  },
  payment: {
    history: [],
    loading: false,
    error: null,
    totalPages: 1,
    currentPage: 1,
  },
  tickets: {
    tickets: [],
    pagination: { currentPage: 1, totalPages: 0, totalCount: 0 },
    isLoading: false,
    error: null,
  },
  dashboard: {
    stats: {
      unreadNotificationsCount: 0,
      cartItemCount: 0,
      totalPendingJobs: 0,
    },
    isLoading: false,
    error: null,
  },
  notifications: {
    notifications: [],
    pagination: {
      currentPage: 1,
      totalPages: 0,
      totalCount: 0,
      limit: 10,
      hasNextPage: false,
    },
    isLoading: false,
    isLoadingMore: false,
    error: null,
  },
};
